# Limpieza de datos-
A raíz de que los datos elegidos para el proyecto tienen problemas de multiíndice y filas con celdas vacías, se realizará una limpieza de datos para poder trabajar con ellos.

In [14]:
# Cargamos datos y pandas.
import pandas as pd
filename = 'data_raw/DALYs/ghe2021_daly_global_new.xlsx'
df = pd.read_excel(filename)
df

     Unnamed: 0 Unnamed: 1                                     Unnamed: 2
0           NaN        NaN   GLOBAL HEALTH ESTIMATES 2021 SUMMARY TABLES:
1           NaN        NaN  GLOBAL DALYs BY CAUSE, AGE AND SEX, 2000-2021
2           NaN        NaN                                            NaN
3           NaN        NaN                                      July 2024
4           NaN        NaN                                            NaN
..          ...        ...                                            ...
199         NaN        NaN             Venezuela (Bolivarian Republic of)
200         NaN        NaN                                       Viet Nam
201         NaN        NaN                                          Yemen
202         NaN        NaN                                         Zambia
203         NaN        NaN                                       Zimbabwe

[204 rows x 3 columns]

Dado que el dataset tiene un multíindice, se usará el método ffill para rellenar las celdas vacías con el valor de la fila anterior. Esto permitirá que cada fila tenga toda la información necesaria para su análisis posterior.

Además, necestimos leer la hoja de excel de los años que nos interesan (2000-2021) y aplicar el método ffill a cada una de ellas para obtener un dataset limpio y listo para su análisis.

In [15]:
# Lectura de hoja "Global 2021"
G2021= pd.read_excel(filename, sheet_name="Global 2021")
G2021
# Lectura de hoja "Global 2020"
G2020 = pd.read_excel(filename, sheet_name="Global 2020")
G2020
# Lectura de hoja "Global 2019"
G2019 = pd.read_excel(filename, sheet_name="Global 2019")
G2019
# Lectura de hoja "Global 2015"
G2015 = pd.read_excel(filename, sheet_name="Global 2015")
G2015
# Lectura de hoja "Global 2010"
G2010 = pd.read_excel(filename, sheet_name="Global 2010")
G2010
# Lectura de hoja "Global 2000"
G2000 = pd.read_excel(filename, sheet_name="Global 2000")
G2000

,"Global Health Estimates 2021: DALYs by age, sex and cause",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Region:,NaN,NaN,NaN,NaN,Global,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Year:,NaN,NaN,NaN,NaN,2000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,Sex,Both sexes,Male,Female,Male,...,NaN,NaN,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,1600,NaN,B.,Intentional injuries,NaN,NaN,83089863.774205,58807843.84866,24282019.925546,4235.333334,...,2376202.45647,1357440.243563,3553.073572,779472.278086,1862746.571592,10391030.843898,7253898.18563,1822739.596923,1184268.079432,984311.357284
219,1610,NaN,NaN,1.,Self-harm,NaN,38803829.2269,24808274.937737,13995554.289163,0,...,1562659.816852,1018020.525966,0,0,437161.731173,6397796.353007,4401362.034539,1227773.427125,807626.623524,723834.119795
220,1620,NaN,NaN,2.,Interpersonal violence,NaN,33398624.062209,25232198.289918,8166425.772291,1971.575644,...,721527.790261,321637.760517,1550.773268,679092.799896,852058.267098,3012838.812642,2512954.145329,536738.033304,335212.281355,235980.720034
221,1630,NaN,NaN,3.,Collective violence and legal intervention,NaN,10887410.485097,8767370.621005,2120039.864092,2263.75769,...,92014.849357,17781.95708,2002.300304,100379.47819,573526.573321,980395.67825,339582.005762,58228.136493,41429.174553,24496.517455
222,1700,NaN,C.,Other COVID-19 pandemic-related outcomes,NaN,NaN,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
# Usamos el método ffill para rellenar las celdas vacías con el valor de la fila anterior.
# Realizamos este proiceso a cada una delas hojas que leímos con aterioridad.

G2021 = G2021.ffill()
G2020 = G2020.ffill()
G2019 = G2019.ffill()
G2015 = G2015.ffill()
G2010 = G2010.ffill()
G2000 = G2000.ffill()

In [17]:
# Guardamos cada año como un excel limpio en capeta data_clean.
G2021.to_excel('data_clean/DALY_ffill_2021.xlsx', index=False, sheet_name='Global 2021')
G2020.to_excel('data_clean/DALY_ffill_2020.xlsx', index=False, sheet_name='Global 2020')
G2019.to_excel('data_clean/DALY_ffill_2019.xlsx', index=False, sheet_name='Global 2019')
G2015.to_excel('data_clean/DALY_ffill_2015.xlsx', index=False, sheet_name='Global 2015')
G2010.to_excel('data_clean/DALY_ffill_2010.xlsx', index=False, sheet_name='Global 2010')
G2000.to_excel('data_clean/DALY_ffill_2000.xlsx', index=False, sheet_name='Global 2000')

PermissionError: [Errno 13] Permission denied: 'data_clean/DALY_ffill_2000.xlsx'

## Objetivo de la remodelación y limpieza de datos.

Lo que se observa en los conjuntos de datos que se generaron para cada año es que aún los nombres de las columnas se mantienen como unnamed. Lo que queremos conseguir es que cada columna sea una variable y cada obseración sea una fila. El resultado al que se quiere llegar es el siguiente:

| Nombre de la variables  | Descripción     |
| :-------------: | :------------- |
| categoria_principal | Categoría principal de la enfermedad |
| categoria_nivel1 | Subcategoría |
| categoria_nivel2 | Subsubcategoría (si la hay) |
| nombre_enfermedad | Nombre de la enfermedad. Es el nivel más bajo dentro de las categorías de la OMS.|
| codigo| Código según la OMS. |
| ano | Año correspondiente de la hoja. |
| sexo | Sexo de la persona afectada. |
| edad_min | Límite inferior del rango de edad.|
| edad_max | Límite superior del rango de edad.|
| dalys | Valor numérico de los DALYs para la enfermedad. |

**Tabla 1:** Objetivo de la remodelación y limpieza de datos. Se busca que cada columna sea una variable y cada fila una observación.

Por lo tanto, el siguiente paso será remodelar los conjuntos de datos por año para conseguir un formato adecuado para el análisis posterior. Para esto...